# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: fofa

env_files:
  github_token: ~/.github_token
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - 
    main: cmd/fofa/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm64
    asmflags:
      - -D mysymbol
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
      - ./dontoptimizeme=-N
    ldflags:
      - "-s -w"
      - "-X 'main.version={{.Version}}'"
      - "-X 'main.commit={{.Commit}}'"
      - "-X 'main.date={{.Date}}'"
      - "-X 'main.builtBy={{.Env.USER}}'"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
